version: "3.1"
services:
  mongodb:
    image: mongo
    container_name: mongodb-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: '12345'
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db