version: '3'
services:
  ticket-service:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
    depends_on:
      - flight-service

  flight-service:
    build:
      context: ./flight-service
      dockerfile: Dockerfile
    ports:
      - '4001:4001'
    environment:
      - PORT=4001
